sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: *
  alioss:
    endpoint: oss-ap-northeast-1.aliyuncs.com
    access-key-id: *
    access-key-secret: *
    bucket-name: heima-sky-takeout
